Main Architecture
vitali-anku/AppTestTask pull request #1
Opened 2018-12-05 13:07 UTC by vitali-anku

1)package struct
2)empty class, interface
3)model: marvelService, storage file, repository->characters file
4) presenter: base file, characters file
5)ui: characters file, gloal file, main file
6) empty MyApp

2018-12-05 13:24 UTC, CraggyHaggy requested changes

2018-12-05 13:24 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/MyApplication.kt
> +class MyApplication {
Rename this class as `TaskApp`. If you create this file, then it shoulld be extended from `Application`.

2018-12-05 13:24 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/data/MarvelService.kt
> +interface MarvelService {
Don't add empty files, if they aren't used.

2018-12-05 13:24 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/data/storage/Prefs.kt
> +class Prefs {
Don't add empty files, if they aren't used.

2018-12-05 13:24 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/data/storage/RawAppData.kt
> +class RawAppData {
Don't add empty files, if they aren't used.

2018-12-05 13:24 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/characters/CharactersRepository.kt
> +class CharactersRepository {
Don't add empty files, if they aren't used.

2018-12-05 13:24 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/base/BasePresenter.kt
> +class BasePresenter {
This file must be extended from `Moxy` `Presenter`.

2018-12-05 13:24 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +class CharactersPresenter {
This file must be extended from `BasePresenter` and be connected with `CharactersView`.

2018-12-05 13:24 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersView.kt
> +interface CharactersView {
This file must be extended from `Moxy` `View`.

2018-12-05 13:24 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/characters/CharactersFragment.kt
> +
You must add empty `Fragment` to draw it into tabs.

2018-12-05 13:24 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/main/MinFragment.kt
> +class MinFragment {
Rename this class as `MainFragment`.

2018-12-08 13:25 UTC, vitali-anku commented
Create: MainFragment+Presenter; CharacterFragment+View+Presenter+layout; LikeCharactersFragment+View+Presenter+layout; AboutMeFragment+View+Presenter+layout
created a switch bottomNavigationView + implementation of switches and display on the screen

2018-12-10 10:06 UTC, CraggyHaggy requested changes

2018-12-10 10:06 UTC, CraggyHaggy commented on app/build.gradle
> +//    implementation "com.google.dagger:dagger-android-support:$dagger_android_support"
Don't leave commented code in project. Just remove it.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/TaskApp.kt
> +        lateinit var newsComponent: AppComponent
Make `setter` for this method `private`.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/di/AppComponent.kt
> +interface AppComponent {
Format this code.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/di/module/AppModule.kt
> +
Remove empty line.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/aboutme/AboutMePresenter.kt
> +class AboutMePresenter @Inject constructor(): BasePresenter<AboutMeView>(){
Rename screen chain as `Profile`.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/aboutme/AboutMeView.kt
> +    fun showText(str: String)
If this method is temporary, then you must add `TODO`. The same logic must be applied to other `Presenter`.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/likecharacters/LikeCharactersPresenter.kt
> +        super.onFirstViewAttach()
Always add empty line after `super` method call.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/likecharacters/LikeCharactersPresenter.kt
> +class LikeCharactersPresenter: BasePresenter<LikeCharactersView>() {
Rename screen chain as `FavoriteCharacter`.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/AppPresenter.kt
> +class AppPresenter: MvpPresenter<MvpView>()
Remove this `Presenter`, it is unused.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/main/MainPresenter.kt
> +class MainPresenter: BasePresenter<MvpView>()
Remove this `Presenter`, it is unused.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/AppActivity.kt
> +        setTheme(R.style.AppTheme)
Put this line into `AndroidManifest`.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/AppActivity.kt
> +        setContentView(R.layout.layout_container)
Rename `layoutId` according to class.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/AppActivity.kt
> +        if(savedInstanceState==null){
Format this condition.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/AppActivity.kt
> +            supportFragmentManager.beginTransaction().replace(R.id.container, MainFragment()).commit()
Use tabulation for method chains.
```
supportFragmentManager.beginTransaction()
               .replace(R.id.container, MainFragment())
               .commit()
```

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/global/BaseFragment.kt
> +    private var instanceStateSaved: Boolean = false
Why did you copy this variable from `GitFox`? It is unused, so remove.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/global/BaseFragment.kt
> +abstract class BaseFragment : MvpAppCompatFragment() {
Remove all unused variables and methods.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/main/MainFragment.kt
> +        retainInstance = true
Why did you use this `retainInstance = true`? It is **MISTAKE**!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/main/MainFragment.kt
> +                    .apply {
Don't use `apply` for this block, just method chain. Where is `hide, show` logic?

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/res/layout/fragment_main.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Use `LinearLayout` to prevent overlay.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/main/MainFragment.kt
> +        if(savedInstanceState==null){
Why did you split this logic with above?

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/main/MainFragment.kt
> +
What is the empty line?

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/main/MainFragment.kt
> +            childFragmentManager.beginTransaction().apply {
Move this logic to `onCreate` method chain.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/main/MainFragment.kt
> +                    }.commitNow()
Also, you must check, when the `Fragment` is restored and `show/hide` values is restored too?

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/main/MainFragment.kt
> +    private val mOnNavigationItemSelectedListener =
Change with lambda in    `bottom_navigation_view.setOnNavigationItemSelectedListener(mOnNavigationItemSelectedListener)`.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/main/MainFragment.kt
> +        if(tag != currentTabTag){
Format this code.

2018-12-10 10:06 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/main/MainFragment.kt
> +            childFragmentManager.beginTransaction().apply {
Change `apply` with method chain.

2018-12-11 09:26 UTC, vitali-anku commented
check my task

2018-12-17 12:07 UTC, CraggyHaggy requested changes

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/di/AppComponent.kt
> +@Component(modules = arrayOf(AppModule::class))
Format this code.

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/AppPresenter.kt
> +class AppPresenter: MvpPresenter<MvpView>()
Really remove!!!

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/aboutme/ProfilePresenter.kt
> +class ProfilePresenter @Inject constructor(): BasePresenter<ProfileView>(){
Format this code!!!!!!

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/aboutme/ProfileView.kt
> +interface ProfileView: MvpView{
Format this code!!!!!!

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +class CharactersPresenter @Inject constructor (): BasePresenter<CharactersView>(){
Format this code!!!!!!

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +        viewState.showText("Characters")
In those cases always add `TODO` in the next template : "// TODO: [key]( characters tab) (Add view implementation)".

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersView.kt
> +interface CharactersView : MvpView{
Format this code!!!!!!

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/aboutme/ProfileView.kt
> +@StateStrategyType(AddToEndStrategy::class)
Why do you use this strategy?

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersView.kt
> +@StateStrategyType(AddToEndStrategy::class)
Why do you use this strategy?

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/favorites/FavoritesPresenter.kt
> +        viewState.showText("LikeCharacters")
ALWAYS add empty line after `super` method call.

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/favorites/FavoritesView.kt
> +@StateStrategyType(AddToEndStrategy::class)
Why do you use this strategy?

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/favorites/FavoritesPresenter.kt
> +        viewState.showText("LikeCharacters")
Add `TODO`.

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/AppActivity.kt
> +        setTheme(R.style.AppTheme)
REALY!!!!!

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/AppActivity.kt
> +        setContentView(R.layout.layout_container)
DO YOU READ, what i have written?

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/AppActivity.kt
> +        if(savedInstanceState==null){
Format this code!!!!!!

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/about_me/ProfileFragment.kt
> +import kotlinx.android.synthetic.main.fragment_about_me.*
Don't use this `extension`. Remove it and use `findViewById`.

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/about_me/ProfileFragment.kt
> +    override val layoutRes: Int
Remove type and getter.

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/characters/CharactersFragment.kt
> +class CharactersFragment: BaseFragment(), CharactersView {
See `ProfileFragment`.

2018-12-17 12:07 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/favorites/FavoritesFragment.kt
> +class FavoritesFragment: BaseFragment(), FavoritesView {
See `ProfileFragment`.

2018-12-17 16:22 UTC, vitali-anku commented
+ TODO
+ format code
+ use findViewById
+ deleted format and get
+ edited package
+ deleted strategy by view
+ deleted Profile

2018-12-18 06:32 UTC, CraggyHaggy requested changes

2018-12-18 06:32 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +        // TODO: characters tab
You forgot a description -> `// TODO: characters tab (Add implementation for tab)`.

2018-12-18 06:32 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersView.kt
> -interface CharactersView : MvpView{
Why did you remove strategy? I have been interested in your choice.

2018-12-18 06:32 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/AppActivity.kt
> +            supportFragmentManager.beginTransaction().replace(R.id.container, MainFragment())
Move `replace` to new line.

2018-12-18 06:32 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/AppActivity.kt
> +            supportFragmentManager.beginTransaction().replace(R.id.container, MainFragment())
Also one interested moment about this logic : in `Activity` you use `commit`, but in `Fragment` - ` commitNow`? Is it good?

2018-12-18 06:32 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/characters/CharactersFragment.kt
> +        view!!.findViewById<TextView>(R.id.test_characters).text = str
`view!!.findViewById` is bad because of `findViewById` perfomance lack. You must make it `lateinit` and init into `onViewCreated`.

2018-12-18 09:41 UTC, CraggyHaggy requested changes

2018-12-18 09:41 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +        // TODO: characters tab (viewState.showText("123"))
What does `(viewState.showText("123"))` mean?

2018-12-18 09:41 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/characters/CharactersFragment.kt
> +    lateinit var charactersText: TextView
Make it `private`.

2018-12-18 09:41 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/global/BaseFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
Validate `BaseFragment` for useless methods and variables to remove it.

2018-12-18 13:10 UTC, CraggyHaggy requested changes

2018-12-18 13:10 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/global/BaseFragment.kt
>      private var instanceStateSaved: Boolean = false
Remove this field too.

2018-12-18 13:37 UTC, CraggyHaggy approved these changes

2018-12-18 13:37 UTC, merged