create feature/drawing_adapter
vitali-anku/AppTestTask pull request #10
Opened 2019-01-04 09:04 UTC by vitali-anku

- create adapter
- create holder for adapter
- create favorite

2019-01-04 09:31 UTC, CraggyHaggy requested changes

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/entity/charactrers/Character.kt
> +    val apiCharacter: ApiCharacter,
Don't pass Data entity into Domain, but just remove `@SerializedName` and return all fields and fill with server values.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +        character.favorite = !favorite
Make this method return `Single<Character>`, also you must save into `Prefs` this value.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/entity/charactrers/Character.kt
> +    var favorite: Boolean
Make it `val` and use `copy` method instead of mutability.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +                    {
Make one line.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/CharactersInteractor.kt
> +            }
You make it on `UI-thread`.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +    fun getCharacters(): Single<List<Character>> = Single
Move `Single` to new line.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +                        val position = apiCharacters.indexOf(apiCharacter)
Refactor this method according to `Map` impl.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/storage/Prefs.kt
> +    var favoritesCharacters: MutableList<Boolean>?
Instead of this implementation, keep ` Map<Id, Character>` with only favorite objects.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/storage/Prefs.kt
> +    private val FAVORITE_CHARACTER = "favorite_characters"
Rename this as `FAVORITE_CHARACTERS`.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/storage/Prefs.kt
> +class Prefs @Inject constructor(context: Context, val gson: Gson) {
Format this constructor.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +    private val sharedPreference: Prefs
Rename field as `prefs`.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +    fun favoriteCharacter(character: Character, favorite: Boolean): Completable {
`Presenter` shouldn't return anything.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +    fun favoriteCharacter(character: Character, favorite: Boolean): Completable {
Pass `position` in the adapter to update it later.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/characters/CharactersFragment.kt
> +        adapter = CharactersAdapter(context!!, characters, this)
You must create `Adapter` in `onViewCreated` and later just fill it.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/global/CharactersAdapter.kt
> +    val characters: List<Character>,
Remove `characters` param, and make `context` as `private`.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/global/CharactersAdapter.kt
> +    private val listener: CharactersView
Don't pass `CharactersView`, instead pass lambda as `(int, Character) -> Unit`.

2019-01-04 09:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/global/CharactersAdapter.kt
> +        holder.itemView.setOnClickListener {
Use `DiffUtil` to notify `RecyclerView`.

2019-01-08 16:15 UTC, vitali-anku commented
- add reight entity Character
- add Diffutil
- edited adapter, fragment, presenter, prefs and repositpory and interactor

2019-01-08 16:40 UTC, vitali-anku commented
- edited Presenter (copy class)
- edited var by Character field
- edited save prefs in Repository

2019-01-09 08:55 UTC, CraggyHaggy requested changes

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/CharactersInteractor.kt
>              Completable.fromAction {
Make `Repository` returns `Completable` instead of `Interactor` composing it.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/CharactersInteractor.kt
> +                    .observeOn(schedulers.ui())
Move thread logic to `Repository`.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/entity/charactrers/Character.kt
> +    var favorite: Boolean?
Why it is `nullable`? Refactor it, please.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +    fun getCharacters(): Single<List<Character>> =
Change method order according to call:
```
fun a() {
       b()
       c()
}

private b()
private c()
```

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +    private fun getApiCharacters() = marvelService
Remove this method and use `marvelService.getCharacters` in `Single.zip` with `characterDataWrapper` in `BiFunction`.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +    private fun getPrefs(): Single<Map<Int, Character>> =
Remove this method and use `Single.just(prefs.favoritesCharacters)` in `Single.zip`.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +                            if (favorites.containsKey(id)) {
Evaluating favorite state will be crashed according to `Map<Int, Character>?`. Refactor this logic, please.
Make this logic one line.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +        prefs.favoritesCharacters?.let {
Why do you call it on `UI-thread`?

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/storage/Prefs.kt
> +    context: Context,
Make it `private val`.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/storage/Prefs.kt
> +    private fun convertArrayToMutableList(valueString: String?): MutableMap<Int, Character> {
Remove this logic and keep `Map` as `JSON` -> https://stackoverflow.com/questions/8360836/gson-is-there-an-easier-way-to-serialize-a-map.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +        val character = characters[position]
Make this RxJava chain method.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersView.kt
> +    fun favorCharacter(characters: List<Character>)
Remove this method and use `showCharacters` always.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/characters/CharactersFragment.kt
> +        Log.e("Error", message)
If you add logs to vcs, it should be displayed only in debug.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/global/CharactersAdapter.kt
> +    private val listener: (position: Int) -> Unit
Rename listener according to context.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/global/CharactersAdapter.kt
> +        super.onBindViewHolder(holder, position, payloads)
Do you need `super` call?

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/global/CharactersAdapter.kt
> +        val character = characters[position]
You don't need two versions of `onBindViewHolder`. If `payloads` are empty, then use `holder.bind(character)`, else `holder.updateStar(character.favorite!!)`.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/global/CharactersAdapter.kt
> +    fun updateCharacters(newCharacters: List<Character>) {
Rename this method as `setCharacters(characters:..)`.

2019-01-09 08:55 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/ui/global/CharactersAdapter.kt
> +    private var characters = mutableListOf<Character>()
Rename field as `items`.

2019-01-09 10:52 UTC, vitali-anku commented
- edited naming methods and fields
- deleted some methods
- edited logic repository/presenter

2019-01-11 15:28 UTC, vitali-anku commented
- edited URI in MarvelService
- edited CharactersRepository
- removed nullable preferences value

2019-01-11 15:29 UTC, vitali-anku commented
Sorry, I made a little mud

2019-01-11 15:59 UTC, vitali-anku commented
- removed textView in fragment_characters
- format menu menu file

2019-01-14 08:22 UTC, CraggyHaggy requested changes

2019-01-14 08:22 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/CharactersInteractor.kt
> +    fun setFavoriteCharacter(position: Int): Single<MutableList<Character>>? =
Return `Single<Character` instead of `List<Character`.

2019-01-14 08:22 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +    private val characters = mutableListOf<Character>()
Remove this collection, because we don't implement cache at this time.

2019-01-14 08:22 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +                        .flatMap { characterDataWrapper ->
Use `map` instead of `flatMap`.

2019-01-14 08:22 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +        val character = characters[position].copy(favorite = !characters[position].favorite)
You implement all this logic on UI-thread and just pass it into the Rx-chain. Save these values into `Prefs`.

2019-01-14 08:22 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/storage/Prefs.kt
> +    private fun convertCharacters(gsonString: String?): MutableMap<Int, Character> {
Rename `gsonString` as `json`.

2019-01-14 08:22 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +                                id,
Use `with(it)` construction.

2019-01-14 08:24 UTC, CraggyHaggy requested changes

2019-01-14 08:24 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +                    apiCharacters.size
Remove these two lines.

2019-01-14 09:24 UTC, vitali-anku commented
- edited parameters and return value in CharactersInteractor
- replaced flatMap on map in Repository
- edited Char-presenter
- edited name parameter in Prefs-class

2019-01-15 15:45 UTC, CraggyHaggy requested changes

2019-01-15 15:45 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/CharactersInteractor.kt
> +    fun setFavoriteCharacter(character: Character): Single<Character> =
Remove type definition and rename method as `favorCharacter`.

2019-01-15 15:45 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +                BiFunction<List<ApiCharacter>, Map<Int, Character>?,
`Prefs` should return not nullable return.

2019-01-15 15:45 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +            Single.just(character)
Change with `Single.fromCallable()`.

2019-01-15 15:45 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +                    .subscribeOn(schedulers.newThread())
Why do you use `newThread()` instead of `io()`?

2019-01-15 15:45 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +                        val favoriteCharacters = prefs.favoritesCharacters
Rename `favoriteCharacters` as `characters` and `favoriteCharacter` as `newCharacter`.

2019-01-15 15:45 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/CharactersRepository.kt
> +                            prefs.favoritesCharacters = favoriteCharacters
This line is duplicated in two branches. Move it from the condition.

2019-01-15 15:45 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/storage/Prefs.kt
>          val mutableList = mutableMapOf<Int, Character>()
Rename it as `characters`.

2019-01-16 08:41 UTC, vitali-anku commented
- removed type definition and removed method in interactor
- removed nullable and edited method favorCharacter Prefs in Repository
- rename smt in CharPresenter and Prefs
- update version kotlin

2019-01-16 12:52 UTC, CraggyHaggy requested changes

2019-01-16 12:52 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/CharactersInteractor.kt
> +            charactersRepository.getCharacters()
Make it one line method.

2019-01-16 12:59 UTC, vitali-anku commented
formated CharactersRepository

2019-01-16 13:00 UTC, vitali-anku commented
- formated CharactersInteractor

2019-01-16 13:05 UTC, CraggyHaggy approved these changes

2019-01-16 13:05 UTC, merged