Feature/business logic
vitali-anku/AppTestTask pull request #3
Opened 2018-12-18 15:35 UTC by vitali-anku

create:
+ entity
+ Characters interactor and his methods

2018-12-18 16:25 UTC, CraggyHaggy requested changes

2018-12-18 16:25 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +class CharactersPresenter @Inject constructor(var charactersInteractor: CharactersInteractor) :
You shouldn't change `Presentation` in this commit, because it is only `Domain`.

2018-12-18 16:25 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/CharactersInteractor.kt
> +    fun favorFavoritesCharacters() {}
What is the difference between `setFavoritesCharacters` and `favorFavoritesCharacters`?

2018-12-18 16:25 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/CharactersInteractor.kt
> +class CharactersInteractor @Inject constructor(
Methods must have params and return values.

2018-12-18 16:25 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/CharactersInteractor.kt
> +class CharactersInteractor @Inject constructor(
This is pr for the first tab, so you must add only associated `UseCases`.

2018-12-19 11:17 UTC, vitali-anku commented
edited interactor, presenters
+ add repository
+ add service
+ gradle impl RxJava, Gson, retrofit

2018-12-19 12:31 UTC, CraggyHaggy requested changes

2018-12-19 12:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/Interactor.kt
> +interface Interactor {
Don't use interfaces for `Interactor` and `Repository` at this time.

2018-12-19 12:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/di/module/MarveModule.kt
> +    fun provideCharactersInteractoir(marvelRepository: MarvelRepository): CharactersInteractor =
Remove this value.

2018-12-19 12:31 UTC, CraggyHaggy commented on app/build.gradle
> +    implementation("com.jakewharton.rxrelay2:rxrelay:$retrofit")
Why do you add it?

2018-12-19 12:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/di/module/RetrofitModule.kt
> +class RetrofitModule {
Remove it.

2018-12-19 12:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/di/module/RetrofitModule.kt
> +    private class CustomFieldNamingPolicy : FieldNamingStrategy {
Remove this class.

2018-12-19 12:31 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/repository/MarvelRepository.kt
> +class MarvelRepository(private val marvelApi: MarvelService) {
It is "solyanochka". Make it consinstently according to context

2018-12-19 15:44 UTC, CraggyHaggy requested changes

2018-12-19 15:44 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/CharactersInteractor.kt
> +    fun getCharacters(ts: String, apikey: String, hash: String) {
You shouldn't pass all these values through the chain call. This information will be included by `Repository`.

2018-12-19 16:10 UTC, vitali-anku commented
in

2018-12-19 16:49 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/CharactersInteractor.kt
> +    fun setFavoritCharacter(id: Int, like: Boolean): Completable = Completable.complete()
Rename `like` as `favorite`.

2018-12-19 17:03 UTC, merged

2018-12-19 17:13 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/interactor/characters/CharactersInteractor.kt
> +    fun setFavoritCharacter(id: Int, favor: Boolean): Completable = Completable.complete()
Change method signature as `fun setFavoriteCharacter(id: Int, favorite: Boolean)...`.