add 1 part drawing
vitali-anku/AppTestTask pull request #9
Opened 2018-12-20 15:00 UTC by vitali-anku

create this branch and first commit

2018-12-26 16:05 UTC, CraggyHaggy requested changes

2018-12-26 16:05 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/base/BasePresenter.kt
> +    protected fun unsubscribeOnDestroy(disposable: Disposable) {
Make it extension.

2018-12-26 16:05 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +class CharactersPresenter @Inject constructor(private val charactersInteractor: CharactersInteractor) :
```
class CharactersPresenter @Inject constructor(
          private val charactersInteractor: CharactersInteractor
) :  BasePresenter<CharactersView>() {
```

Format in the next way.

2018-12-26 16:05 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +                .subscribeOn(Schedulers.io())
We discussed the schedulers logic two days before. Create `SchedulersProvider` as it done in `GitFox`.

2018-12-26 16:05 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +                .subscribe({ characterDataWrapper ->
Format `subscribe` as 

```
subscribe(
       {},
       {}
)
```

2018-12-26 16:05 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +                    hideProgress()
Move `hideProgress` into `doAfterTerminate`.

2018-12-26 16:05 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +    private fun hideProgress() {
This method is useless. Remove it.

2018-12-26 16:05 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +                        viewState.showError(error as Throwable)
Pass `String` instead of `Throwable`. Remember, that `View` is weak.

2018-12-26 17:31 UTC, vitali-anku commented
- add schedulers interface + implementation
- fixed Dagge2+Moxy
- add lib in build.gradle
- add extension in BaseFragment

2018-12-27 09:18 UTC, vitali-anku commented
- add schedulers interface + implementation
- fixed Dagge2+Moxy
- add lib in build.gradle
- add extension in BaseFragment

2018-12-27 10:38 UTC, CraggyHaggy requested changes

2018-12-27 10:38 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/base/BasePresenter.kt
> +    protected fun Disposable.unsubscribeOnDestroy() {
Rename this method as `connect`.

2018-12-27 10:38 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +    private var charactersInteractor: CharactersInteractor,
Make it `val`.

2018-12-27 10:38 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +                .subscribeOn(schedulersProvider.io())
Move thread logic to `Repository`.

2018-12-27 10:38 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +                    { characterDataWrapper ->
Remove `characterDataWrapper` and use `it`.

2018-12-27 10:38 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +                    { errorMessage ->
Remove `errorMessage` and use `it`.

2018-12-27 10:38 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersView.kt
> +    fun showError(errorMessage: String)
Rename `errorMessage` as `message`.

2018-12-27 10:38 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +                        viewState.showError(errorMessage.toString())
Also you must create `ErrorHandler` to map errors into `String` message. See `GitFox` implementation.

2018-12-27 11:46 UTC, vitali-anku commented
- add ErrorHandler
-  thread -> Repository
- edited naming

2018-12-27 16:52 UTC, vitali-anku commented
- add ErrorHandler
-  thread -> Repository
- edited naming

2018-12-28 10:00 UTC, CraggyHaggy requested changes

2018-12-28 10:00 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +                        viewState.showCharacters(it.data.results)
Format this block.

2018-12-28 10:00 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +                    { it ->
Rename param.

2018-12-28 10:00 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/model/system/ResourceManager.kt
> +class ResourceManager @Inject constructor(private val context: Context) {
Format this constructor.

2018-12-28 10:00 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/extension/HumanView.kt
> +    is HttpException -> when (this.code()) {
Rethink this logic.

2018-12-28 10:39 UTC, vitali-anku commented
- formatted code
- edited errors TypeMessage

2018-12-28 10:56 UTC, CraggyHaggy requested changes

2018-12-28 10:56 UTC, CraggyHaggy commented on app/src/main/java/com/testtask/apptesttask/presentation/characters/CharactersPresenter.kt
> +                        errorHandle.proceed(it) { message -> viewState.showError(message) }
Format it.

2018-12-28 10:58 UTC, CraggyHaggy approved these changes

2018-12-28 10:58 UTC, merged